#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
ENV ASPNETCORE_ENVIRONMENT=Development
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Menubly.Host/Menubly.Host.csproj", "Menubly.Host/"]
RUN dotnet restore "Menubly.Host/Menubly.Host.csproj"
COPY . .
WORKDIR "/src/Menubly.Host"
RUN dotnet build "Menubly.Host.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Menubly.Host.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Menubly.Host.dll"]